debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  mvc:
    view:
      prefix: /view/
      suffix: .html
#  thymeleaf:
#    prefix: classpath:/static/views/
#    suffix: .html
#    check-template-location: true
#    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: fastcampus
    password: kimyena
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always
  data.rest:
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  freemarker:
    template-loader-path: classpath:/templates
    prefix: /freemarker/
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    cache: false
  devtools:
    livereload:
      enabled: true

